######################################################################
##
## Filename: uart_rxd_vrf.udo
## Created on: Tue Apr 30 10:07:38 中国标准时间 2019
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
