######################################################################
##
## Filename: uart_txd_vrf.udo
## Created on: Mon Apr 29 11:32:42 中国标准时间 2019
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
