######################################################################
##
## Filename: vrf_timer_1s.udo
## Created on: Tue Jul 09 16:50:44 中国标准时间 2019
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
